### ISSUE TITLE
Neat idea, bro

### ISSUE THREAD

**Issue by davesque** [xferguson/wordhierarchy#1]
Hey man.  Thought I'd make a kudos "issue".  A word hierarchy is a neat idea.  Might be similar to how the brain arrives at the meaning of words, although I half-suspect that looks more like a loosely-organized graph of related concepts (mind map) than a tree (hierarchy).  Although some words definitely seem to have a hierarchical relationship.  I suppose graphs can look kinda like trees sometimes even if they don't fit the precise definition.

**Comment by xferguson** [comment]
Thanks, man! Yeah, I think it is a bit like a term hierarchy, really. You're right that it's not a real tree in the strictest sense, as the repetition of some terms shows. But the intention is to explore ways of hierarchicalizing the importance of vocabulary when learning. I'm curious how we can approach this question as self-taught language learners. Is it valuable to organize such a chart ourselves? Is that even possible without serious native coaching? Or is this really only better as a teaching tool?

The mind-map description does fit in many ways. Maybe this would work well for some post-thesaurus-parsing visualization.

We'll see as it develops.

**Comment by davesque** [comment]
Cool stuff.  Looking forward to it!  What's your email nowadays?  I might
visit Seattle soon.  I'll have to pay you a visit.  Had fun time hanging
out with Chris Danielson for a couple of days recently.
